version: '3.8'

services:
  ghost:
    image: ghost:3-alpine
    restart: always
    ports:
      - ${PORT}:2368
    volumes:
      - ${HOST_DATA_VOLUME}:/var/lib/ghost/content
    environment:
      url: ${URL}
      database__client: sqlite3
      mail__transport: SMTP
      mail__from: ${HOST_EMAIL}
